import type { Metadata } from "next";
import ReduxProvider from "@/utils/redux/reduxProvider";
import {  Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';

const hindSiliguri = Hind_Siliguri({
  weight: ["400", "500", "600", "700"],
  subsets: ["bengali", "latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased   ${hindSiliguri.className}`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
